driver:
  name: openstack
platforms:
  - name: test-reboot
provisioner:
  playbooks:
    cleanup: cleanup.yml
    playbook: playbook.yml
scenario:
  # Rebooting is not an idempotent task.
  test_sequence:
    - lint
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
