language: python
dist: xenial
python:
  - "2.7"
  - "3.7"
cache: pip

install:
  - pip install -U pip
  - pip --version
  - pip install ansible ansible-lint yamllint flake8 molecule
  - ansible-lint --version
  - yamllint --version
  - flake8 --version
  - molecule --version

script:
  - molecule lint -s openstack
  - flake8 $(find . -name '*.py')

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
