language: python
python:
  - "2.7"
  - "3.7"
cache: pip

install:
  - pip install -U pip
  - pip --version
  # We want everything in requirements.txt except shade,
  # since we only test docker in travis
  - pip install $(grep -v shade < requirements.txt)
  - ansible-lint --version
  - yamllint --version
  - flake8 --version
  - molecule --version

script:
  - molecule lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
