# role tasks
- name: Install cockpit
  yum:
    name: "{{ cockpit_version }}"
    state: present
  become: "{{ cockpit_become }}"
  become_user: "{{ cockpit_become_user }}"

- name: Start cockpit
  service:
    name: cockpit.socket
    state: started
    enabled: true
  become: "{{ cockpit_become }}"
  become_user: "{{ cockpit_become_user }}"
