- name: Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_and_groups_add_groups }}"
  become: "{{ users_and_groups_become }}"
  become_user: "{{ users_and_groups_become_user }}"

- name: Add group members
  user:
    name: "{{ item['name'] }}"
    state: present
    groups: "{{ item['groups'] }}"
    append: true
  with_items: "{{ users_and_groups_add_group_members }}"
  become: "{{ users_and_groups_become }}"
  become_user: "{{ users_and_groups_become_user }}"

- include_tasks: remove_group_members.yaml
  with_items: "{{ users_and_groups_remove_group_members }}"

- name: Remove groups
  group:
    name: "{{ item }}"
    state: absent
  with_items: "{{ users_and_groups_remove_groups }}"
  become: "{{ users_and_groups_become }}"
  become_user: "{{ users_and_groups_become_user }}"
