# role tasks
- name: Install cockpit
  yum:
    name: "{{ cockpit_version }}"
    state: present
  become: true
  become_user: "{{ cockpit_become_user }}"

- name: Start cockpit
  service:
    name: cockpit
    state: started
    enabled: yes
  become: true
  become_user: "{{ cockpit_become_user }}"
