# role tasks

- name: Find the current locale setting
  slurp:
    src: /etc/locale.conf
  register: host_locale

- name: update locale if needed
  become: "{{ localectl_become }}"
  become_user: "{{ localectl_become_user }}"
  command: localectl set-locale LANG="{{ localectl_locale}}"
  when: localectl_locale not in host_locale.content | b64decode

- name: Find the current keymap setting
  slurp:
    src: /etc/vconsole.conf
  register: host_keymap

- name: update keymap if needed
  become: "{{ localectl_become }}"
  become_user: "{{ localectl_become_user }}"
  command: >
    localectl set-keymap --no-convert "{{ localectl_keymap }}"
  when: localectl_keymap not in host_keymap.content | b64decode

- name: Find the current x11_keymap setting
  slurp:
    src: /etc/X11/xorg.conf.d/00-keyboard.conf
  register: host_x11_keymap

- name: update x11keymap if needed
  become: "{{ localectl_become }}"
  become_user: "{{ localectl_become_user }}"
  command: >
    localectl set-x11-keymap --no-convert "{{ localectl_x11_keymap }}"
  when: localectl_x11_keymap not in host_x11_keymap.content | b64decode
