# role tasks
- name: Verify chronyd is installed
  package:
    name: "{{ chrony_package }}"
    state: present
  become: true
  become_user: "{{ chrony_become_user }}"

- name: Edit chrony config file
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
  become: true
  become_user: "{{ chrony_become_user }}"
  notify:
    - Restart chrony service

- name: Enable chronyd service
  service:
    name: chronyd
    state: started
    enabled: true
  become: true
  become_user: "{{ chrony_become_user }}"
