# role tasks
- name: Provision VM (OVF)
  include_tasks: deploy_ovf.yml
  with_items: "{{ vmware_provision_OVFs }}"

- name: Provision VM (CUSTOM)
  include_tasks: manage_vm.yml
  with_items: "{{ vmware_provision_custom_VMs }}"
