# role tasks
- name: Create temp variable to store UUIDs
  set_fact:
    uuids: []

- name: provision VM (OVF)
  include_tasks: deploy_ovf.yml
  with_items: "{{ vmware_provision_OVFs }}"

- name: provision VM (CUSTOM)
  include_tasks: manage_vm.yml
  with_items: "{{ vmware_provision_VMs }}"
