# role tasks
- name: provision VM
  include_tasks: deploy_ovf.yml
  when: vmware_provision_from_ovf is true

- name: provision VM
  include_tasks: manage_vm.yml
  when: vmware_provision_from_ovf is false