dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-kdump
    image: rhel-7.5-server-x86_64-updated
    flavor: m1.medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  config_options:
    defaults:
      stdout_callback: yaml
scenario:
  name: openstack
verifier:
  name: testinfra
  lint:
    name: flake8
  directory: ../shared/
