dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: molecule-instance
    image: rhel-7.6-server-x86_64-updated
    flavor: ci.m1.tiny
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  lint:
    name: flake8
