dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-nfs_server
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  config_options:
    default:
      stdout_callback: yaml
verifier:
  name: testinfra
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
  lint:
    name: flake8
