dependency:
  name: galaxy
  options:
    role-file: molecule/openstack/requirements.yml
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-nfs_server
    image: rhel-7.4-server-x86_64-updated
    flavor: m1.medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
scenario:
  name: openstack
verifier:
  name: testinfra
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
  lint:
    name: flake8
