- hosts: all
  roles:
    - role: oasis_roles.system.rhsm
      when: ansible_distribution == 'RedHat'
      rhsm_username: "{{ lookup('env', 'OASIS_RHSM_USERNAME') }}"
      rhsm_password: "{{ lookup('env', 'OASIS_RHSM_PASSWORD') }}"
      rhsm_server_hostname: "{{ lookup('env', 'OASIS_RHSM_SERVER_HOSTNAME') }}"
      rhsm_pool_ids: "{{ lookup('env', 'OASIS_RHSM_POOL_IDS') }}"
      rhsm_repositories:
        enable:
          - rhel-7-server-rpms
          - rhel-7-extras-rpms
    - role: oasis_roles.system.firewalld
      firewalld_zone: public
      firewalld_ports_open:
        # rpc-bind /usr/lib/firewalld/services/rpc-bind.xml
        - proto: tcp
          port: 111
        - proto: udp
          port: 111
        # mountd /usr/lib/firewalld/services/mountd.xml
        - proto: tcp
          port: 20048
        - proto: udp
          port: 20048
        # NFSv4 /usr/lib/firewalld/services/nfs.xml
        - proto: tcp
          port: 2049
