dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: instance_fedora
    image: fedora:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  lint:
    name: flake8
