dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: fed_test1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
  inventory:
    group_vars:
      all:
        # yamllint disable-line rule:line-length
        ansible_ssh_private_key_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/id_rsa"
        ansible_user: fedora
    host_vars:
      localhost:
        openstack_provision_volumes:
          - display_name: openstack_provision1
            size: 10
          - display_name: openstack_provision2
            size: 5
        openstack_provision_servers:
          - name: fed_test
            flavor: ci.m1.tiny
            image: 'Fedora 29'
            cloud: default
            key_name: openstack_provision
            groups:
              - test_group
            volumes:
              - openstack_provision1
              - openstack_provision2
        openstack_provision_keypairs:
          - name: openstack_provision
            public_key_file: "{{ ansible_ssh_private_key_file }}.pub"
verifier:
  name: testinfra
  lint:
    name: flake8
