driver:
  name: openstack
platforms:
  - name: rhsm-basic-subscription
    groups:
      - rhsm
provisioner:
  playbooks:
    converge: playbook.yml
  inventory:
    links:
      group_vars: ../shared/group_vars
