- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - name: molecule_openstack_ci
      vars:
        molecule_openstack_ci_state: present
        molecule_openstack_ci_cloud: default
