dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-openstack_provision
    image: rhel-7.4-server-x86_64-updated
    flavor: m1.medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
scenario:
  name: default
  # There should be no create or destroy executed because of this
  # being a provisioning role. Also, there should be no prepare step,
  # as the local host needs to have itself prepared, and we don't want
  # to mess with the developer's localhost.
  create_sequence: []
  check_sequence:
    - converge
    - check
  converge_sequence:
    - converge
  destroy_sequence: []
  test_sequence:
    - lint
    - dependency
    - syntax
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
  directory: ../shared/
