dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test_server
    flavor: m1.medium
    image: 'CentOS-7-x86_64-GenericCloud-released-latest'
    count: 2
    cloud: default
    groups:
      - test_group
  - name: fed_test
    flavor: m1.medium
    image: 'Fedora 29'
    cloud: default
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
scenario:
  name: default
  # There should be no create or destroy executed because of this
  # being a provisioning role. Also, there should be no prepare step,
  # as the local host needs to have itself prepared, and we don't want
  # to mess with the developer's localhost.
  create_sequence: []
  check_sequence:
    - converge
    - check
  converge_sequence:
    - destroy
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - dependency
    - syntax
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
  directory: ../shared/
