dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-molecule_openstack_ci
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
scenario:
  name: default
verifier:
  lint:
    name: flake8
