- name: converge
  hosts: localhost
  roles:
    - role: openstack_provision
      openstack_provision_servers:
        - name: test_server
          flavor: m3.medium
          image: 'CentOS-7-x86_64-GenericCloud-released-latest'
          count: 2
          groups:
            - test_group

- name: run tests
  hosts: localhost
  tasks:
    - name: debug output
      debug: var=item
      with_items: "{{ groups['test_group'] }}"
