- name: converge
  hosts: localhost
  roles:
    - role: openstack_provision
      openstack_provision_servers:
        - name: test_server
          flavor: m1.medium
          image: 'CentOS-7-x86_64-GenericCloud-released-latest'
          count: 2
          cloud: default
          groups:
            - test_group
        - name: fed_test
          flavor: m1.medium
          image: 'Fedora 29'
          cloud: default

- name: run tests
  hosts: localhost
  tasks:
    - name: debug output
      debug: var=item
      with_items: "{{ groups['test_group'] }}"
