galaxy_info:
  author: Author Name
  description: Set the default DNS servers for your system to resolve names
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
