driver:
  name: openstack
volumes:
  - name: gluster_gdeploy_vol0_ver
    size: 10
  - name: gluster_gdeploy_vol1_ver
    size: 10
  - name: gluster_gdeploy_vol2_ver
    size: 10
  - name: gluster_gdeploy_vol3_ver
    size: 10
platforms:
  - name: test-gluster_gdeploy0_ver
    volumes:
      - gluster_gdeploy_vol0_ver
      - gluster_gdeploy_vol1_ver
  - name: test-gluster_gdeploy1_ver
    volumes:
      - gluster_gdeploy_vol2_ver
      - gluster_gdeploy_vol3_ver
provisioner:
  inventory:
    group_vars:
      all:
        gluster_version: "-3.1.3.0"
