dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: chrony
    image: centos/systemd
    privileged: true
    command: /usr/lib/systemd/systemd --system
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
scenario:
  name: docker
verifier:
  name: testinfra
  lint:
    name: flake8
