driver:
  name: docker
platforms:
  - name: molecule_docker_ci
    image: centos:7
provisioner:
  name: ansible
  playbooks:
    docker:
      create: ../shared/create.yml
      destroy: ../shared/destroy.yml
