driver:
  name: openstack
platforms:
  - name: test_server1
  - name: fed_test1
provisioner:
  playbooks:
    converge: ../shared/playbook.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
  inventory:
    group_vars:
      all:
        ansible_ssh_private_key_file: >-
          {{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/id_rsa_default
    host_vars:
      localhost:
        openstack_provision_servers:
          - name: test_server
            flavor: ci.m1.tiny
            image: 'CentOS-7-x86_64-GenericCloud-released-latest'
            count: 2
            groups:
              - test_group
          - name: fed_test
            flavor: ci.m1.tiny
            image: 'Fedora 29'
