name: Test with Ansible

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'  # A build will already happen for the commit, don't also build the tag
  pull_request: {}
  schedule:
    - cron: '12 0 * * *'

env:
  TOX_ANSIBLE_DRIVER: docker
  ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/:~/work/
  checkout_path: ansible_collections/oasis_roles/system

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
          - cockpit
          - chrony
          - disk_wipe
          - firewalld
          - localectl
          - molecule_docker_ci
          - nfs_server
          - nmcli_add_addrs
          - package_updater
          - passwd
          - passwordless_ssh
          - register_idm
          - sshd
          - system_repositories
          - timezone
          - users_and_groups
          - update_ca_trust
          - upload_files
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: ${{ env.checkout_path }}
      - name: update submodules to latest
        run: |
          cd "${{ env.checkout_path }}"
          git submodule update --remote --recursive
      - name: Setup pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-modules
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade pip
          pip install tox tox-ansible
      - name: Test with tox
        run: |
          set -ex
          # There is some magic in the "mv" command that makes ansible-galaxy work
          # I haven't found any logic for it, but if you don't do this mv, then
          # the dependency step in molecule when run from tox will fail
          mv ansible_collections ~/work/
          cd ~/work/${{ env.checkout_path }}
          tox --ansible-role ${{ matrix.role }}
