name: Test with Ansible

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: '12 0 * * *'

env:
  TOX_ANSIBLE_DRIVER: docker
  ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/:~/work/
  checkout_path: ansible_collections/oasis_roles/system

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
          - cockpit
          - chrony
          - disk_wipe
          - firewalld
          - libvirtd
          - localectl
          - molecule_docker_ci
          - network_scripts
          - nfs_server
          - nmcli_add_addrs
          - package_updater
          - passwd
          - passwordless_ssh
          - register_idm
          - sshd
          - system_repositories
          - timezone
          - users_and_groups
          - update_ca_trust
          - upload_files
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: ${{ env.checkout_path }}
      - name: update submodules to latest
        run: |
          cd "${{ env.checkout_path }}"
          git submodule update --remote --recursive
      - name: Setup pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-modules
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y libapt-pkg-dev build-essential python3-setuptools
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install tox tox-ansible
      - name: Test with tox
        run: |
          set -ex
          # There is some magic in the "mv" command that makes ansible-galaxy work
          # I haven't found any logic for it, but if you don't do this mv, then
          # the dependency step in molecule when run from tox will fail
          mv ansible_collections ~/work/
          cd ~/work/${{ env.checkout_path }}
          tox --ansible-role ${{ matrix.role }}

  release:
    needs: build  # Only release if the build is good
    if: startsWith(github.ref, 'refs/tags/')  # Only release if there is a tag that's been pushed to the repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Create release artifacts
        run: |
          ansible-galaxy collection build
          ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
      - name: Release artifacts to Git Hub
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./oasis_roles-system*.tar.gz
          allowUpdates: true
          name: Rlease ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
